//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeEquipmentRepair.DB
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Request
    {
        demEntities dem = new demEntities();
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int requestID { get; set; }
        public System.DateTime startDate { get; set; }
        public int idTechType { get; set; }
        public string TechType
        {
            get
            {
                var type = dem.TypeTechs.FirstOrDefault(c=>c.idType == idTechType);
                return type.orgTechType;
            }
        }
        public string orgTechModel { get; set; }
        public int idProblem { get; set; }
        public string problem
        {
            get
            {
                var problem = dem.Problems.FirstOrDefault(c => c.idProblem == idProblem);
                return problem.problemDescryption;
            }
        }
        public int idStatus { get; set; }
        public string status
        {
            get
            {
                var statu = dem.Statuses.FirstOrDefault(c => c.idStatus == idStatus);
                return statu.requestStatus;
            }
        }
        public Nullable<System.DateTime> completionDate { get; set; }
        public string repairParts { get; set; }
        public Nullable<int> masterID { get; set; }
        public int clientID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Problem Problem { get; set; }
        public virtual Status Status { get; set; }
        public virtual TypeTech TypeTech { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
